mnemonic = ""        # НУ МНЕМОНИЧЕСКАЯ ФРАЗА
derivation_path = "" # ПУТЬ ДЕРИВАЦИИ, ПО ДЕФОЛТУ m/44'/118'/0'/0/0
prefix = ""          # ПРЕФИКС НУЖНОГО БЛОКЧЕЙНА celestia ДЛЯ ЦЕЛЕСТИИ inj ДЛЯ ИНЖЕКТИВА
chain_id = ""        # АЙДИ БЛОКЧЕЙНА, ИЩИТЕ В ДОКАХ ИЛИ Я ХЗ
denom = ""           # ТОКЕН БЛОКЧЕЙНА UTIA ДЛЯ ЦЕЛЕСТИИ
memo = ""            # НУ САМО СООБЩЕНИЕ КОТОРОЕ ОТПРАВЛЯЕТСЯ
rpc = ""             # ССЫЛКА НА РПС НОДУ НАХУУУУУЙ
gas_price = 0        # ГАЗ ПРАЙС ЕБАНЫЙ
gas_adjustment = 0   # КОРРЕКТИРОВКА ГАЗА
times = 1000000      # КОЛИЧЕСТВО ИТЕРАЦИЙ
